name: 'blazor_service'
services:
  web:
    image: blazor_service:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - 80:443
    volumes:
      - log:/app/CoreLogs
        
    #For production
      - ~\.aspnet\https\:/https/
    #For production

    #For development
    # - ~\.aspnet\https\:/root/.aspnet/https/
    # - ~\AppData\Roaming\Microsoft\UserSecrets\:/root/.microsoft/usersecrets/
    #For development

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
    #For production
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PFX_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${PFX_LINUX_PATH}
    #For production
    
    depends_on:
      - rabbit_mq
        
  rabbit_mq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbit'
    restart: on-failure
    ports:
      - '15660:15672'
      - '5660:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  log: